### ISSUE TITLE
Add physics objects to each element

### ISSUE THREAD

**Issue by willrogers** [razvanvasile/RML#18]
Each element object should contain one object that represents its physics parameters.  Each of these objects should inherit from `ElementPhysics`: `DriftPhysics`, `MagnetPhysics`, `DipolePhysics` etc.  These can be defined in `physics.py`.
- The ElementType can be used to determine which physics object to create when creating an element.
- The attributes of the physics objects can be determined from those in THERING in AT:
  - All physics objects should have a length
  - Magnets should have poly_a, poly_b etc.
  - Dipole magnets should have gap, entrance angle, exit angle etc.

The physics objects should have setters and getters for each of their fields:
- `get_poly_a()`
- `set_poly_a()`

etc.

The **second table** on this page http://confluence.diamond.ac.uk/display/~hgs15624/Requirements+for+PML shows the fields that each class should have.

@mfurseman: you can help by finding the fields for the elements in MML that aren't listed in the table.

**More advanced (ask Matt for help)**

Finally, the `get_pv_value()` and `set_pv_value()` methods on elements should be altered to have the additional argument `sim=False`.  If `sim` is true, the value should be got or set on the physics object, not on the device.

For this, we have to match up the field from RML (`x` and `y` for BPMs, 'b1' for quadrupoles) to the corresponding fields.  So we'd need `get_x()` and `get_y()` for BPMs and `get_b1()` and `set_b1()` for quadrupoles.  We can have a Quadrupole class that inherits from Magnet for this.

**Comment by willrogers** [comment]
@mfurseman will help you find the correct type of object in MML/AT.

**Comment by willrogers** [comment]
This change may mean that the unit conversion object need to be stored in the Element, not in the device.

**Comment by razvanvasile** [comment]
[Link](https://github.com/razvanvasile/RML/blob/master/rml/physics.py) to the physics file
